### ISSUE TITLE
Zonas verdes en España

### ISSUE THREAD

**Issue by alc1020** [alc1020/SEMINARIO_FUENTES#1]
Descarga de Green R y recopilación de los datos de las zonas verdes en España

**Comment by CarmenRu** [comment]
Aunque ya esta puesto el label os hago un texto con lo que necesito específicamente, tengo descargado el greenR que es lo necesario para sacar los datos de zonas verdes en España lo que aun no tengo claro es como usar R en este ámbito para sacar las graficas y las imágenes visuales necesarias, os paso la URL donde lo estoy mirando: https://github.com/sachit27/greenR/tree/main/R 
Esta en su repositorio subido de tema 5 en el apartado de greenR y luego dentro de una carpeta que pone R

**Comment by CarmenRu** [comment]
Si se os ocurre algo me pasais que comando poner por aquí para que nadie mas se tenga que descargar greenR que tardó un poquito en cargar.

**Comment by alc1020** [comment]
Ok, ahora lo reviso a ver que puedo hacer

**Comment by alc1020** [comment]
greenR en proceso de instalación
