### ISSUE TITLE
Datos meteorológicos

### ISSUE THREAD

**Issue by CarmenRu** [alc1020/SEMINARIO_FUENTES#3]
Recopilación desde AEMET de los datos meteorológicos en España.

**Comment by stg1004** [comment]
- Horas de sol
- Nubes
- ...

**Comment by stg1004** [comment]
Pendiente de recibir respuesta por parte de Aemet Open data para obtener los datos de horas de insolación y de nubes.

**Comment by stg1004** [comment]
Aemet sigue sin contestar. Esperando respuesta.

**Comment by stg1004** [comment]
Datos subidos de las horas de luz del mes de octubre por provincias en formato json y csv.
